### ISSUE TITLE
Beta testing errors

### ISSUE THREAD

**Issue by saumyabhadani95** [CSDL-USF/Rockwell#105]
We tested the app with members of lab on Nov 29 and we saw the following two errors:
* [ ] Error while inserting tweets into the DB (see below) @saumyabhadani95 
* [ ] In attention checks both Yes and No radio buttons can be selected and once a radio button is selected it cannot be unselected. @RobertAndion 

# Database error
```
KeyError
KeyError: 'data'
Traceback (most recent call last)
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/ubuntu/infodiversity-mock-social-media/backend/src/authorizer/twauth-web.py", line 129, in callback
worker_id = resp_worker_id.json()["data"]
KeyError: 'data'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.
You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

Error in Database server : 
```
3.144.234.59 - - [29/Nov/2021 18:58:58] "GET /insert_user?twitter_id=1034483868747882496&account_settings=%7B%22time_zone%22:%20%7B%22name%22:%20%22Pacific%20Time%20(US%20&%20Canada)%22,%20%22utc_offset%22:%20-28800,%20%22tzinfo_name%22:%20%22America/Los_Angeles%22%7D,%20%22protected%22:%20false,%20%22screen_name%22:%20%22meghnach24%22,%20%22always_use_https%22:%20true,%20%22use_cookie_personalization%22:%20false,%20%22sleep_time%22:%20%7B%22enabled%22:%20false,%20%22end_time%22:%20null,%20%22start_time%22:%20null%7D,%20%22geo_enabled%22:%20false,%20%22language%22:%20%22en%22,%20%22discoverable_by_email%22:%20true,%20%22discoverable_by_mobile_phone%22:%20true,%20%22display_sensitive_media%22:%20false,%20%22allow_contributor_request%22:%20%22all%22,%20%22allow_dms_from%22:%20%22following%22,%20%22allow_dm_groups_from%22:%20%22following%22,%20%22translator_type%22:%20%22none%22%7D HTTP/1.1" 200 -
ERROR!!!! invalid input syntax for type json
LINE 2: ...        VALUES('2929015320','2021-11-29 18:59:34','{"time_zo...
                                                             ^
DETAIL:  Token ""Pacific Time (US " is invalid.
CONTEXT:  JSON data, line 1: {"time_zone": {"name": "Pacific Time (US
```

**Comment by RobertAndion** [comment]
Both buttons being selectable can be solved by using a controlled form. The documentation for the current bootstrap child elements being used should have an example of this. It will wrap the existing code
