### ISSUE TITLE
Error loading timeline with zero tweets

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#56]
I got this error when loading from my other account `@glcdev`. I suspect this may have to do with the fact that I do not follow anybody so the home timeline should return zero tweets.

```
Connect
500 TypeError: /home/ubuntu/Truman/views/script.pug:41
   39|    
   40|     -var ii = 0;
 > 41|     input(type='hidden', id='session_input', name=script[0].session_id, value=_csrf)
   42|     each val in script
   43|       -ii = ii + 1
   44|       -console.log(ii)
Cannot read property 'session_id' of undefined
   at eval (eval at wrap (/home/ubuntu/Truman/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:704:107)
   at template (eval at wrap (/home/ubuntu/Truman/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1497:120)
   at Object.exports.renderFile (/home/ubuntu/Truman/node_modules/pug/lib/index.js:427:38)
   at Object.exports.renderFile (/home/ubuntu/Truman/node_modules/pug/lib/index.js:417:21)
   at View.exports.__express [as engine] (/home/ubuntu/Truman/node_modules/pug/lib/index.js:464:11)
   at View.render (/home/ubuntu/Truman/node_modules/express/lib/view.js:135:8)
   at tryRender (/home/ubuntu/Truman/node_modules/express/lib/application.js:640:10)
   at Function.render (/home/ubuntu/Truman/node_modules/express/lib/application.js:592:3)
   at ServerResponse.render (/home/ubuntu/Truman/node_modules/express/lib/response.js:1012:7)
   at ServerResponse.res.render (/home/ubuntu/Truman/node_modules/express-flash/lib/express-flash.js:29:16)
   at axx.get.then (/home/ubuntu/Truman/controllers/script.js:96:19)
   at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by saumyabhadani95** [comment]
Unfortunately the current code is written in a way that there has to be atleast one post for the feed to show. I don't want to make any major changes before the beta test tomorrow so I will mail everyone to follow some accounts on Twitter so that their feeds are not empty. I will take care of this bug after the beta testing. Thank you for catching this!

**Comment by RobertAndion** [comment]
When there are no tweets it is now detected and notifies the user, we would also move them to a page and ask them to sign in with another twitter account if that is preferable.

**Comment by RobertAndion** [comment]
I have added a landing page to handle feeds with no tweets, however it needs testing.
